personalInfo:
  firstName: 'John'
  lastName: 'Doe'
  # Date of birth (MM/DD/YYYY)
  dob: '01/01/2001'
  # Use real email to get appointment infomation
  email: ''
  # Not really needed but good to have a real one
  lastFourSSN: '1001'
  # If you want to recieve notificaion through phone, if not keep blank
  # WARNING: Use number only (Ex: 111111111)
  phoneNumber: ""

location:
  # The time interval (in ms) the app will recheck for newer dates
  interval: 10000
  # Zipcode of your location
  zipCode: '75067'
  # Filter DPS location by distance from the zipcode
  miles: 15
  # Put empty ('') for any day
  preferredDays: 'Monday'
  # Put true/false without quotes if you want to book only same day appointment
  sameDay: false